### ISSUE TITLE
Format a sheet with user inputs into the code, and capture run metadata

### ISSUE THREAD

**Issue by DavidZong** [ppreshant/WW-CoV2-project#1]
We want to make an input sheet that tracks the inputs to the script so we can only change the input sheet from week to week. We need to determine what information is needed. And we need to change the code to read the sheet and make sure this format works.

**Comment by ppreshant** [comment]
Copy pasted segments from code here with the variable names 
### qPCR 
```
std_par <- tibble(                       # Input the slope and intercept from standard curve of various primer pairs/targets here - Target should match Target field (provided in excel sheet - Sample input reference.csv) 
  target = c('BRSV_N', 'BCoV_M', 'N1_CoV2', 'N2_CoV2', 'N1_multiplex',  'N2_multiplex', 'pMMoV_Vgp1'),
  slope =  c(-3.61,    -3.18,    -2.98,     -3.12,     -3.08,           -3.06,           -3.13),
  intercept = c(38,     34.77,       39,        40,        38,              37,              35.87) # values for various targets
)
template_volume <- 4 # ul template volume in qPCR reaction
```
### ddPCR

`template_volume <- 10 /22 * 20 # ul template volume per well of the ddPCR reaction`

### .rmd file

```
Spike in and concentration details
HA_concentration_factor <- 1000 # concentration factor of wastewater -> RNA
elution_volume <- 50 # ul - RNA extraction final volume

copies/ul viral suspension spiked in (Spike ID: S16)
all_spike_virus_conc <- tibble(Target = c('BCoV_M', 'BRSV_N'), spike_virus_conc = c(10609, NA))
spike_virus_volume <- 50 # ul of viral suspension spiked in x ml WW; (x ~ 350 - 450 and varies for each sample)

 sheets to read from qPCR data dump excel file
read_these_sheets <- c('dd.WW6_706-1_N1/N2', 'dd.WW7_706-2_N1/N2', 'WW28_706-1_BCoV', 'WW29_706-2_BCoV_Std13')
title_name <- '706 Rice'

Biobot ID sheet
bb_sheets <- c('Week 13 (7/6)')

Extra categories for plotting separately (separate by | like this 'Vaccine|Troubleshooting')
extra_categories = 'Std|TR2' # for excluding this category from a plot, make the switch (exclude_sample = TRUE)
```


Once this data is templated in a sheet; the data has to be imported (read_sheet) and then each parameter extracted into individual variables or the code changed to accomodate the variables within the data table object (called tibble)

**Comment by ppreshant** [comment]
_Only 3 variables need to be changed every week_

# sheets to read from qPCR data dump excel file
```
read_these_sheets <- c( 'dd.WW28_824_N1/N2',
                        'WW59_824_BCoV_Std42')
title_name <- '824 Rice'
```
# Biobot_id sheet
`bb_sheets <- c('Week 20 (8/24)')`

Additionally regular expression for recognizing baylor_wells can be given next to each plate in read_these_sheets for processing baylor samples

**Comment by ppreshant** [comment]
The sheet from which input parameters are being read can be updated by adding run information and metadata. This is going to aid in identifying what information went into the calculation - for better transparency. 
 - So the same sheet works for both input and output metadata!

**Comment by ppreshant** [comment]
Ideas for run metadata -- 
1. (last, least important) All values for constants used in the calculations that are not inputs in the sheet
2. Sample distribution (total # of rows input = WWTP + manhole + controls) tally
