### ISSUE TITLE
Client error: (429) : Quota exceeded limit of 'Read requests per 100 seconds'

### ISSUE THREAD

**Issue by ppreshant** [ppreshant/WW-CoV2-project#26]
I occassionally get this error message when doing `read_sheet()` over multiple google sheets in a short duration of time.

**Full error message**
```
Error: Client error: (429) RESOURCE_EXHAUSTED
  * Either out of resource quota or reaching rate limiting. The client should look for google.rpc.QuotaFailure error detail for more information.
  * Quota exceeded for quota group 'ReadGroup' and limit 'Read requests per 100 seconds' of service 'sheets.googleapis.com' for consumer 'project_number:603366585132'.

Error details:
  * Error details of type 'google.rpc.Help' are not implemented yet.
  * Workaround: use `tryCatch()` and inspect error payload yourself.
  * Please open an issue at https://github.com/r-lib/gargle/issues, so we can fix.
```

This can be solved by creating a google cloud platform project and getting service account (or an API key) to run with the google sheets API through the R package. Here is a great [reference](https://github.com/tidyverse/googlesheets4/issues/139) linked to a document with all the necessary details. 

Can you figure out how to set this up @DavidZong ?

**Comment by DavidZong** [comment]
made a file called [enable_api.r](https://github.com/ppreshant/WW-CoV2-project/blob/issue26/enable_api.r) in branch [issue26](https://github.com/ppreshant/WW-CoV2-project/tree/issue26).
To use:
Restart R studio to clear your old token.
Paste in keys (can't upload these to github because security)
Source enable_api.r.
Run a command to read a sheet, it should ask you to log in to an app called CovidWW.

**Comment by ppreshant** [comment]
Works great now! 

It should be good for right now, but is there anyway this authentication can be done only once and then stored, just like it stores the google account pre-authorized? 

In case someone else in our group (Camille knows R) wants to use this, what would be the best practice for this API authentication? Since we can't paste the keys here, it looks like everyone should have this enable_api.r file in their local computer with the keys pasted with the file not tracked in the git, or somehow it should not be pushed to remote.

Is there any other way we can apply this?

**Comment by DavidZong** [comment]
The API keys should only really be used for heavy use cases. For typical weekly processing, not running enable_api.r will allow you to use your own personal login as usual.

**Comment by ppreshant** [comment]
That makes sense. Thank you for the clarification
