### ISSUE TITLE
Fix column renaming for when there's no BCoV data

### ISSUE THREAD

**Issue by DavidZong** [ppreshant/WW-CoV2-project#35]
In https://github.com/ppreshant/WW-CoV2-project/blob/WW_master/2-calculations_multiple_runs.R on rows 293-300, causes a crash if we don't have BCoV data since it tries to rename a column that doesn't exist

**Comment by ppreshant** [comment]
Oops, I fixed that in `formula_show` - it was from line 295 - Will merge tonight
