### ISSUE TITLE
Date Column In Report

### ISSUE THREAD

**Issue by DavidZong** [ppreshant/WW-CoV2-project#37]
Fix date column in the report to match the date that the sample was collected.

**Comment by DavidZong** [comment]
in 2-calculations_multiple_runs.R

mutate(Date = title_name %>% str_extract('[:digit:]{3,4}') %>% str_replace('([:digit:]+)([:digit:]{2})', '\\1/\\2/20') ,

This line needs to be changed to look at the sample date. Not the date written in the title

**Comment by DavidZong** [comment]
[1203-1217 Rice Bayou TEST manhole samples.xlsx](https://github.com/ppreshant/WW-CoV2-project/files/5730978/1203-1217.Rice.Bayou.TEST.manhole.samples.xlsx)

Still not right yet. See rows with 12/17. The date still reads 12/16.

This is probably caused by the harmonize_week() function which should be run on WWTP samples but not on Bayou or Manholes.

I'll work on this bug today.

**Comment by ppreshant** [comment]
Oh, sorry. That was actually intentional for the WWTP samples - since we
use both Monday and Tuesday dates, I changed the tuesday ti Mondays date..

I have to not do this for bayou and manhole samples, maybe will put a if
condition with a switch. I will work on it tonight.

**Comment by ppreshant** [comment]
Since WWTP names are hard-coded and only Monday dates are used henceforth, `Harmonize_week()` has been removed in the [B117_pipeline_integration](https://github.com/ppreshant/WW-CoV2-project/tree/B117_pipeline_integration) branch
