### ISSUE TITLE
Fix sample type to grab sample if it was a grab

### ISSUE THREAD

**Issue by DavidZong** [ppreshant/WW-CoV2-project#38]
In the report the it says composite no matter what and needs to say grab if it is a grab.

**Comment by DavidZong** [comment]
Not sure if there's a way to program this with our current data. We don't even record this information at the moment. Will need to update maybe the registry to support.

**Comment by ppreshant** [comment]
I think the bayou is always grab? If you can confirm that with Lillian, we
can program it using the "b" prefix we were going to add to the
abbreviations
