### ISSUE TITLE
Prevent unintentional overwrites to google sheets

### ISSUE THREAD

**Issue by ppreshant** [ppreshant/WW-CoV2-project#4]
Can check for presence of a sheet matching the `flnm` argument; if already present, ask for user feedback for overwrite for each sheet

**Comment by DavidZong** [comment]
I wrote a new write_sheet() that takes this into account called check_ok_and_write() in the general_functions.R file. https://github.com/ppreshant/WW-CoV2-project/commit/fb2ff284a5eb678959e4318867b23b82f48af0ce

I also wrote a testing script in the same branch and tested some conditions. It seems to work okay.

To do: 

- change the write_sheet() function calls to the new function in the various scripts that write to google sheets.
- further testing
- pull request to WW master

**Comment by ppreshant** [comment]
Awesome! Will merge now

**Comment by ppreshant** [comment]
Upon testing, I found that the `menu()` and `askYesNo()` functions only work in interactive mode and do not work while knitting rmd files.
<Could rewrite code in .R and call rmd from there only for making plots>

**Comment by ppreshant** [comment]
Rewrote the markdown into a .R. Solves the interactivity issue #21
