### ISSUE TITLE
get_template_for() returns the wrong well positions (in some cases)

### ISSUE THREAD

**Issue by DavidZong** [ppreshant/WW-CoV2-project#41]
If there are duplicate column names in the Calculations platemap sheet, it causes the get_template_for() function to fail. We either need to program some robustness into the code, or prevent editing of the column and row names in the plate maps.

**Comment by ppreshant** [comment]
Maybe could make it default or fixed to full plate to avoid this?

**Comment by ppreshant** [comment]
Check for <> , 1 : 12 in `colnames()` and A:H in first column `[,'<>']` and throw and error if not matching
