### ISSUE TITLE
Missing manhole samples in excel sheet sent to HHD

### ISSUE THREAD

**Issue by camillejm89** [ppreshant/WW-CoV2-project#55]
Date of issue: 3/12/21
File: 2-calculations
Branch: B117 integration

Manhole samples that were not automatically reported in polished excel sheet for HHD:

NHs [Focused Care Beechnut, Focused Care of Westwood, Memorial City Health & Rehab]
Schools [BENAVIDEZ EL, BONNER EL,  EDISON MIDDLE, ENERGIZED FOR EXCELLENCE ACADEMY EL, GREGG EL, HOUSTON MATH SCIENCE AND TECHNOLOGY CENTER, NEFF ECC, NEFF EL, NORTH FOREST H S, NORTHLINE EL, SANCHEZ EL, SEGUIN EL, SHARPSTOWN INTERNATIONAL SCHOOL, SOUTHMAYD EL]

* Sample were listed in complete data sheet.

**Comment by ppreshant** [comment]
Thanks for making this issue! I will try running the dd.WW148 and see if I
can reproduce this error today

**Comment by ppreshant** [comment]
@camillejm89 I fixed this issue now. Thanks for bringing it up. It's in the B117_pipeline branch
