### ISSUE TITLE
Creating QX-600 Branch Using New Droplet Volume and 22.1uL Reaction Volume

### ISSUE THREAD

**Issue by kmp11** [ppreshant/WW-CoV2-project#68]
We need to change the calculations to account for the increased droplet volume size in the QX600 calculations, and for the increased reaction volume size from using the 40x FRP and mastermix calculator (22.1uL). 

Possibly for now, we can create another prompt on the User Inputs Template to determine if the script should use this branch instead of the main. However, this branch will eventually be merged to the main branch once we switch over to using the QX-600 full time.

Deadline for this by 5-24-23.

**Comment by ppreshant** [comment]
Issue #66 has details about the calculations for new droplet volume. How did Lauren decide to solve this issue - should we change the QX-600 data to be like the old one?

**Comment by ppreshant** [comment]
I fixed both the issues and left notes in the code and in the comments for you and Jingjing. Test it and check that things work @kmp11  

And once you generalize with user input so the same code can work for all cases without changing branches : 
- QX-200 
- QX-600 data with 22 ul rxns (in future, if you do it this way)
- QX-600 with 22.1 ul rxns (5PLEX) -- with user input variable from the sheet
Then you can merge this with the main `WW_master` branch and close these two issues

**Comment by ppreshant** [comment]
We went over the reaction volume in Monday morning meeting and decided that all analysis should only have 22 ul (similar to QX-600) 
- _Details_ : Reaction was setup for 22.1 ul total (22.1 mastermix components + 10 template) but ddPCR droplet generation still saw only 22 ul (22 mastermix components + 10 template).
- implies that master mix and primers and probes are just a little bit dilute but the template concentration doesn't change. The clusters might be slightly lower but the actual quantification should still not change hence no correction is required in the code
