### ISSUE TITLE
not letting me PULL so i can update the branch 

### ISSUE THREAD

**Issue by rogit2** [ppreshant/WW-CoV2-project#70]
gives me this error when i click pull 

">>> /usr/bin/git pull
fatal: bad object refs/heads/WW_master 2
error: https://github.com/ppreshant/WW-CoV2-project did not send all necessary objects"

**Comment by ppreshant** [comment]
You need to update the remote/ pulling url to this - `https://github.com/StadlerlabRice/WW-CoV2-project`

**Comment by ppreshant** [comment]
Hey Robert, did you get it to work?

Here's what you probably need to do within the `git bash`

git remote set-url origin https://github.com/StadlerlabRice/WW-CoV2-project


Also need to do this to fix the error I was getting with pushing today -
 git remote set-url --push origin
https://github.com/StadlerlabRice/WW-CoV2-project

Prashant

**Comment by rogit2** [comment]
Hey Prashant,

I was able to update it to that URL but it is still giving me this issue.


>>> /usr/bin/git pull
fatal: bad object refs/heads/WW_master 2
error: https://github.com/StadlerlabRice/WW-CoV2-project.git did not send
all necessary objects

**Comment by ppreshant** [comment]
The `2` might be an addition to the filename or branch you made by mistake? That's probably what the error is saying
`fatal: bad object refs/heads/WW_master **2**`

Check this page - https://stackoverflow.com/questions/72515916/git-fatal-bad-object-refs-heads-2-master

**Comment by ppreshant** [comment]
Any update on this?

**Comment by ppreshant** [comment]
I'm closing this since there's not more updates
