### ISSUE TITLE
`EDMI` being removed from reported data

### ISSUE THREAD

**Issue by ppreshant** [ppreshant/WW-CoV2-project#73]
Robert identified that: EDMI is missed from the final reported data since Feb 2023. 

Kyle: the 'EDIM' bug. I've found it occurs in the 'present_manhole_samples' table. From what I can tell the only function used to filter out the controls is 'samples_to_remove'. 

Resolution
PK - changed user inputs sheet to exactly match to DI rather than partial matches with `regex('^DI$|Blank|std', ignore_case = TRUE)`

Needs to be tested by Kyle et. al.

**Comment by ppreshant** [comment]
@kmp11 can you confirm if this worked and close the issue?

**Comment by kmp11** [comment]
Yes! This issue is resolved.
